### ISSUE TITLE
Unverified app shown on login

### ISSUE THREAD

**Issue by Callum0x50** [Intility/indev#18]
When attempting to log in to his Skoglab test user using `indev login`, @stianfro reported seeing an unverified app notice. We must ensure indev (and all other platform apps) have verified app registrations.

![image](https://github.com/user-attachments/assets/d25380b1-aa0d-40ff-ab5d-06855f0d7236)

**Comment by Callum0x50** [comment]
This is most likely caused by an outdated enterprise application for the Skoglab tenant. Will re-consent and retry.

**Comment by JonasKs** [comment]
I would message Nævdal, I think he's automated this process - of you give him your ClientID

**Comment by Callum0x50** [comment]
Turns out we had forgotten to migrate the CLI to the most current app reg. Currently going through app regs and setting correct client ids. Will verify in next release.

**Comment by Callum0x50** [comment]
New release out now. Waiting for verification.

**Comment by Callum0x50** [comment]
Stian has verified the new release. Closing.
